application:
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
client:
  base_url: "localhost"
  sender_email: "test@gmail.com"